# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:FW3L5jas0w==,iv:56ZUVt/2torExjH7BeAZdVd7PU5MTGj55bQV+CEAWfA=,tag:DXRBlirRow8QsCgYwHP2uQ==,type:str]
    admin-password: ENC[AES256_GCM,data:li2ZomCwAcshyXM=,iv:gkjeM3BSoKBE2LG5pwwtKvSi1kCxPeBfHErPp4lfk04=,tag:gL9geMwgCq7TpTZCvSNJzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eynu35v0tpg9remal6zeecfeg9e84a2qxake027wwgdn02rdfcls7nyv8r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWEh0c2d4QnA4eXNHbXR3
            aCtaMm5qTEh3QmFrd0xudFB3VytpZXIzYUhvCm1NOGNuS2dXZjZUc2JmTDJMSjdQ
            a0VlRE8rczdKc1dCaERHRzZjanl2SW8KLS0tIEpVcVpEWjdpckRlRGxNRnk5K2pV
            V0lycU9Mdk00eHc4WGVKQ0Zab1hqeEUKi6rKdyRK6XQtRGLLzlLACenBkZcmvTwv
            ZRIshxJeUY4hHU6mj6z8QUaXXeMZj5HXQ8C6+4cBnp4nCf09pysvBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-31T21:55:42Z"
    mac: ENC[AES256_GCM,data:tNlJBbD4rRULTe4rp0FNaVYv/BcCEYu5HAw9REaa1KvEZZKyJvnuNRKYN3yFrJCqVvJApS7hzg2cN0PJuV9t3JiBdKtxY8UAIlILQyyBTl814/xFfwKBrHXfbQV84LhhWpRCSsjHhZINh9CTw6TlAVOSw6DvyU6BVd7Tq4zN10I=,iv:dqr/vbhqzv8sEMV7xrpk2zdgTqEXZncVbbVHN3NsuQk=,tag:yt53h2mr+f7Or0qZR/izDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
