---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-l2-pool
  namespace: networking
spec:
  addresses:
    - "${METALLB_LB_RANGE}"
  avoidBuggyIPs: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2
  namespace: networking
spec:
  ipAddressPools:
    - metallb-l2-pool
