---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.13.5
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    fullnameOverride: metallb
