---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: &app recyclarr
  namespace: media
spec:
  schedule: "@daily"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          initContainers:
            - name: render-configs
              image: ghcr.io/k8s-at-home/recyclarr:v2.3.0@sha256:a799b93be9b4cfa3becb6fb5c2adb87eba90b395fc1fd4901c0df22863e28823
              envFrom:
                - secretRef:
                    name: *app
              command:
                - "/bin/bash"
                - -c
              args:
                - "envsubst < /config/recyclarr.yaml > /shared/recyclarr.yaml"
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: shared
                  mountPath: /shared
          containers:
            - name: sonarrs
              image: ghcr.io/k8s-at-home/recyclarr:v2.3.0@sha256:a799b93be9b4cfa3becb6fb5c2adb87eba90b395fc1fd4901c0df22863e28823
              env:
                - name: TZ
                  value: "${TZ}"
              command:
                - /app/recyclarr
              args:
                - sonarr
                - --config
                - /config/recyclarr.yaml
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yaml
                  subPath: recyclarr.yaml
                  readOnly: true
            - name: radarrs
              image: ghcr.io/k8s-at-home/recyclarr:v2.3.0@sha256:a799b93be9b4cfa3becb6fb5c2adb87eba90b395fc1fd4901c0df22863e28823
              env:
                - name: TZ
                  value: "${TZ}"
              command:
                - /app/recyclarr
              args:
                - radarr
                - --config
                - /config/recyclarr.yaml
              volumeMounts:
                - name: shared
                  mountPath: /config/recyclarr.yaml
                  subPath: recyclarr.yaml
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: *app
            - name: shared
              emptyDir: {}
