# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
    namespace: vpn
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:YydR72YrNnoos+Cd41dL0NOKcLxZ3tmiNu/pwULhLKtDvwzI2kLsveBBl2Pd5Rnpk7q/z2/VIed+3f93oARyMEAZI4zdP5xxAF1yA3eRhGNAo9SkRYONfN7bQ/sTCt5mRpGU4R0hUdz+NOreevtlXk0zdwBDXTz7LHnijMehaER84LFg706oELUY9J5D7It4+Vb23bMGgtCZoeVXnqBtdX66g/UXOHEnimNp/c3c7si9nRm/Dgl8pOxUaNWq5L90Ad2TWRTBttKs377qbsNZ3xdfdGYylK6k92+cJTifyURSKC5W0plt8K341B/XBEaC53/tgMFLwCQZygVvUr2xH7dVuPNTHZL1yzPlWzgVDw==,iv:l67VPzcGm8QT/e1UJtkeIPKpeID7iqWh1I6jEmiQBso=,tag:2J4BdUXGUhQG73iUQ4lXRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eynu35v0tpg9remal6zeecfeg9e84a2qxake027wwgdn02rdfcls7nyv8r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWUZHYlB2Q1c3THBkdlhG
            SmNtWTFoMDArdXNwaHpWUVNGeGt2NWNPTXdzCjRTOWQ1Z1p5SEZPc2hTQ25uNWxT
            N2NpRkxxMkRLT0FqNyt1S1hVZnczR00KLS0tIDdqejZEVXZkL3hudXd2WlNrNE85
            UzBFZVRwN0J0dlNMb3oyQ08wclVLQ0kK15nnKWE8159zQbuSMvzmxisCbXSn1x51
            i2XqNqNR//gKd+sUNiT8jXgkPnZdCJ9Pkvx1M6t1LjqfRp/NwJrm3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-12T00:11:14Z"
    mac: ENC[AES256_GCM,data:8LpN+yp4TPwKzTTP6RvHuxm9pNYcqvGP16DTmv5WUxrb/jRHgtio/PRqkZ5ojpRYWJCAeUyoILhV0dAF+kr3eDa0lyQ4YjMAIhySwi0BnCx2cHxi8mFV9tkSPp8H1EdXjVgF/WQMXijEDSdxX5BuUr0H1X44N0+Puob9Ba9GHcE=,iv:niGU48aOL/yPREpjKegMXQECKlqlXB2M/4OQdTwqhRY=,tag:SXPMtwGh7ZtDDqMlfxxjYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
