# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
    namespace: vpn
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:pgijseV0Z+6c/AoTbv4Xbv2DUw2z7wd5ezxAN0NudbpgvBbm19VjVTzB9GbdRAHu+Qagj25SWpddTaOaY75Se/QBvrvKEHQJ/0jTLEq5SSROVvJ8J+TwKyAYUdPJO3g9XRS3wb2M3oAcO9U6E+ZYwtsXVI31pmnbMhTWqr4KLupkthLYl+45d1fJIrlFmhKfwzZSVK8TANaJc1xN168tgmvv2+mHEyAlITAuK6jKan4TUDdp127L09dTW+QXtyDocEUrx3BzoGknjlIRAmKS2CRTGon2dgTZrw1a+pnyuY9fBIXLOkIGM0gFJ3OJXI+UdGc4wi1DyS4lJhOGtcZo6UPCp1s=,iv:Hi8rreRJiIOyKd2kCBghcsqPlWJH8C2bR3WMo5y7vNc=,tag:gx4FP79Y0dkLN3JCLVzR3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eynu35v0tpg9remal6zeecfeg9e84a2qxake027wwgdn02rdfcls7nyv8r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWUZHYlB2Q1c3THBkdlhG
            SmNtWTFoMDArdXNwaHpWUVNGeGt2NWNPTXdzCjRTOWQ1Z1p5SEZPc2hTQ25uNWxT
            N2NpRkxxMkRLT0FqNyt1S1hVZnczR00KLS0tIDdqejZEVXZkL3hudXd2WlNrNE85
            UzBFZVRwN0J0dlNMb3oyQ08wclVLQ0kK15nnKWE8159zQbuSMvzmxisCbXSn1x51
            i2XqNqNR//gKd+sUNiT8jXgkPnZdCJ9Pkvx1M6t1LjqfRp/NwJrm3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-12T17:11:47Z"
    mac: ENC[AES256_GCM,data:Kwq+bO8B2ttDmcHvXcdrFLUib/hgVL/Xu3VLMMvDoytDmiM2asCVYBCb/zoUauinpXNmiCGIhgA3f64M0J4HkGJTyW7hLkFCMWQxd/KitPkaK31Vl+Y/kpR3cfXISzd9wonyE9ZTTWlD+U5iCyX+ANCfa1SlwGRqXGVDZTVULVs=,iv:hMxrquI6MLT459YHghAWjjmIWlbAI9YOG1IMNBxi2gU=,tag:4wexnlnHlIfjxCEm+VApeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
