# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
    namespace: vpn
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:6MnKUxOBmHYWYnIr3WDEIDhGk8xflS364GoYNzM9I43fXTbG0yzZ+VDdZyOrX63Mwys/N+HnDECIvEendyu/zz1IJwd/1dJLtAVIlSIm/z0Kfn9+oLGHbx833LY1AxN1vQACF6tj+/Gd0HkaKAO79UwIGPtd6KotYwMjIdZipt4nJ8CAtAeTJJq+ggrEDDtGvIo4AvxkSkSu6lxIqU2TRXQeZQx32QmtSSGXsq/y34ieCKXcYAU/BSIDrYkyZoW1eJss2sBILVP+8hh2lEzOkUpl6mGMjHQrs5SdghzxkN3LsODCZlCq36gy3G8sSaujO3oE7CL1kwveiPRoAUC3HCRqmH7VFV1k9imC5xEOdw==,iv:3X31wfR1UZYzEPZoMrIqLsJ/0QibOaDnaTvNJ5CEx5c=,tag:g41hXXmkEhOkLOPdn/ZhpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eynu35v0tpg9remal6zeecfeg9e84a2qxake027wwgdn02rdfcls7nyv8r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWUZHYlB2Q1c3THBkdlhG
            SmNtWTFoMDArdXNwaHpWUVNGeGt2NWNPTXdzCjRTOWQ1Z1p5SEZPc2hTQ25uNWxT
            N2NpRkxxMkRLT0FqNyt1S1hVZnczR00KLS0tIDdqejZEVXZkL3hudXd2WlNrNE85
            UzBFZVRwN0J0dlNMb3oyQ08wclVLQ0kK15nnKWE8159zQbuSMvzmxisCbXSn1x51
            i2XqNqNR//gKd+sUNiT8jXgkPnZdCJ9Pkvx1M6t1LjqfRp/NwJrm3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-08T15:07:36Z"
    mac: ENC[AES256_GCM,data:cvgKSTX73NCvmRl47RyxW8KnuUj3YaDr+YBcy705sTAICNsA2fZgc2k1aVsHLcgoobAktIsKX2eGqZt6WXTXTQFbZx9ZmkIhd9hA76CdK7aTj4W13D5LeCaduwALyxHEJO60l2VnHfM+Dcl1panbbTTyHWVTOHx/5grWtF3Ez3g=,iv:h7k8TDybYn2ooK5becvTWTu9OvmDldNbo44jUkjb81g=,tag:zcXFI6nJRl7pjOZ8Lr1RNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
