apiVersion: v1
kind: Secret
metadata:
    name: vpnConfig
    namespace: vpn
stringData:
    vpnConfigFile: ENC[AES256_GCM,data:icXIhY1+OF9vbf1PZHr8NrpOpTn5IXLMu6Fh+HyYzV/dCm/xJhvXpUQLCxZcTOjg3AOg7bvXMzdzAsDJWu7RBPwB+o+dipxRtmpilPq2AB5l1qqBhGSNYSnNLEUZOrNYaTMtz9Zr/66KPVGAIMRa+FS/Ww4HeTbqKEew3S8VpAQ8pgV54AEyqtzHsbhfsBqRiN18isXvniuK5798ROH8V2JsdyqzwXsLVoED6RLlZeDwwb5/qpFa6Fotjb04mIYACKI8E1bB23BLHjHncX0HnOar3W/rSAze4sLHkmltj28sMEZAQFtuiYFJYouegdpjioZAJkAgko1brEGZmwJV86PU3ihlBWzWKBRMAJwSm6iWEwu0ZMimflraaOb6sr6gr4vAN64OQ2mJHuqVONhOPFhABfvcj0HI0P/yruTw1CeMu67r/xdqrZQgvA0Rzf+K40bJ3FMkEnx+ngxKXuNVxYSoeyBnS6RDJcjlN2a1VU337mB+Q878GDZwtFGkayX+2kLBZwc3Us72pz860a3nFjEBUrveaWgWv9znRo7DM2Xlll31PkjyEcLSAc90AL/wFFOjuOTBtwyVJVNjV5llbHWhwxkV4v5ph3KtHo6Wmo0F55YrE2jmxkGrole2UAMP+aEMuUTRvJyiihGB7WAuNp0xq3xx5jZ2t/uXUQxTKLq/flfPD3QUaNJ45ZvzvXg3qxqWyX4RTAse3CDI8xwbnqbvgzfeeIuGyRbceseJhSLmc7azeo32o94jR3283lzz9Lnts7E2vJHmfEitrIANPhuFadTh4D+lOM680zdty3b+dn4WnZAE2T58Jy01MDycldYntx8DClRPHYLVqy/aKz2kboh0o5gIugpC4wI/QphRF/U=,iv:BV45zEq9z3nPDETrvd5P629FTl00rmgtuO/VNOAf2uQ=,tag:ZdzlDdTo+cWwF9mDyDO5yw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eynu35v0tpg9remal6zeecfeg9e84a2qxake027wwgdn02rdfcls7nyv8r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWUZHYlB2Q1c3THBkdlhG
            SmNtWTFoMDArdXNwaHpWUVNGeGt2NWNPTXdzCjRTOWQ1Z1p5SEZPc2hTQ25uNWxT
            N2NpRkxxMkRLT0FqNyt1S1hVZnczR00KLS0tIDdqejZEVXZkL3hudXd2WlNrNE85
            UzBFZVRwN0J0dlNMb3oyQ08wclVLQ0kK15nnKWE8159zQbuSMvzmxisCbXSn1x51
            i2XqNqNR//gKd+sUNiT8jXgkPnZdCJ9Pkvx1M6t1LjqfRp/NwJrm3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-07T20:21:36Z"
    mac: ENC[AES256_GCM,data:PSVKiddD4sl+cVqa5D3YqYLNwbfJ4d49Q+K3znHcIbJmZJKTjlVf484dq5kd9GjCurPCwFpuL0CgaDiR5k5/QZeonIORQhJ8m1x9EYIhPFuJ5Jzz9vShQCosOPt/l2w7KiilsDSY3Xz82RApwHAeYcrXWkImQLrWuJxea45WA38=,iv:cvjvSkgqwy+BJDhIlLymNq8TJ10ztyVKCpfGAXCpv2Y=,tag:df2KdaBf+XKozKTK2p3AJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
