# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vpnconfig
    namespace: vpn
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:jySZo9MDLARgTh0YwSR9CBlm19VnEML5SRTxgtMcyLG1Z8/65+TsRYQvJK/97VILwazOYkV9ts/f4fnfu6pbKL4dBQa1fVARlJ3DKmeHDlFoIf+Go7m3OHs/XotZhy3YEEVLY78SuiUIIxBrUsHBD4jKSJRA6T0he+dMQ6WZm9+0K5vPTkYxlccvfyybx1X0w1W2OuflCFDT+WSju3KJzNv9GjCdS+G0UWhEZRPeLTvBx1crCqRMOdGR8Ho3ZufTuYIb9gVdB2zPI4Hcea+bHf1+j0kR5P2ffobXaGGlhtJBeVd0xEkyQSREYsHRs0FAjaC9nzA0,iv:/QtKNZBlVrj+1dDCbXcvKdhCrPm3KEjqlFCnTxlun84=,tag:55Q2BK3ORGlhOhUJGNJD8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eynu35v0tpg9remal6zeecfeg9e84a2qxake027wwgdn02rdfcls7nyv8r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWUZHYlB2Q1c3THBkdlhG
            SmNtWTFoMDArdXNwaHpWUVNGeGt2NWNPTXdzCjRTOWQ1Z1p5SEZPc2hTQ25uNWxT
            N2NpRkxxMkRLT0FqNyt1S1hVZnczR00KLS0tIDdqejZEVXZkL3hudXd2WlNrNE85
            UzBFZVRwN0J0dlNMb3oyQ08wclVLQ0kK15nnKWE8159zQbuSMvzmxisCbXSn1x51
            i2XqNqNR//gKd+sUNiT8jXgkPnZdCJ9Pkvx1M6t1LjqfRp/NwJrm3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-13T22:24:47Z"
    mac: ENC[AES256_GCM,data:2qX7/KgIteclBbDbGAxM33XvP3i1u3tTD3uXQvKnZrUsoRfRcmThsG5Euc8XR9WLiGBI+5u7UB36KlFqwmmcjJ/tDX5s/ZuYMSg3EgHdjPxGYqexiphr1XmXrV0+RgbG7OBDS6n3lk9NJpeSqsXyNJ2iw1byG2bkSOGqMrlT6t4=,iv:XKf4YYgT86b6vW3hlldbfYyNyjs9bmwSfMobQNf6Cws=,tag:zBJIjp77FAejVr+gS9k0Ag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
