apiVersion: v1
kind: Secret
metadata:
    name: vpnConfig
    namespace: vpn
data:
    vpnConfigFile: ENC[AES256_GCM,data:VSqKUmfUaQ5hD6RDPmXlSdxGMtCcH8DmHg9nSsn1Vw+TaT7pB+gkw92S6rbJpq9L8Dzr7XMzoS1YKD9tXbd7hkY3QeOuRGEsWhXFMUZMFHNXgPw5mvUJeouzwPSddxRDlucyKJd9W428PbeBU3d/HEX4qywLhs44/hn0V4VIq5bTtZyJtHx6VYrSj7u4i/5Ydi/AbRFpdJzfAwQGlHFB5IbFo3Dtf7mbMsD70zbYUEoGZ39vzAQ8Ld+ukW4MBWrxlAPZGAHECLmRGvtai/1O8rq27BltOj5iU11J1CnucB0sK5ceQAxnhNop4nUs3YMyLhb/A7q5Nj/UBX6/5M0gtsR/PAkOYybu07fTgSuFyYf7HgiwPzbx6hqPjNZXNQhoJyYnDLh3eUYj+c+tkaPR4P2fKRJ0BjLEToKLumRL66tkgl0wcYNODlVfyOcbTIFe+aAKRFS9Vyz1SuHw6GPstImqcAXYlLP0fjf9fQTjB5Li1NcR+gpk9SJ7Y/u3PikTqbUzmtQRNiT0p6V4P/FgoL321mB98jx/rYBHAr82yLxqu+Lbwo2xZQMwv1CZii07lH4hjpj19l8Y5kYFfPf8G7YiA6lVUAyMhbwvXia9OXAC9xRCzWsQLHJwWDOl5+nL+WKdS6OVaHCEQJjM0/3VEaDoEiXk8Wqm2icphoUPwKFtTQPpxV+bFJa0iMYi7ZhO6pPt8Lv3+E3CVXWVmHonvV4B5IFxI66LdwYoLpS+Ca91RCRn8/ZgwtCru79+8yLpbCl9z+q1/wZwDjF/Vib3+36GlCWcpzI2yB76L1Uh6vUWqNNdgDoNT0KG3reOKVj5jYH4LDs40YhPLmOgK0SupoB4To0azSkEhPjuD7cap06gOw==,iv:SkL09a8xL/O9lFZPzuPGTEEDWQtqDcjrf/qVLJlej6k=,tag:lSEGsQAWlvi+9DuyoM5+bA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eynu35v0tpg9remal6zeecfeg9e84a2qxake027wwgdn02rdfcls7nyv8r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWUZHYlB2Q1c3THBkdlhG
            SmNtWTFoMDArdXNwaHpWUVNGeGt2NWNPTXdzCjRTOWQ1Z1p5SEZPc2hTQ25uNWxT
            N2NpRkxxMkRLT0FqNyt1S1hVZnczR00KLS0tIDdqejZEVXZkL3hudXd2WlNrNE85
            UzBFZVRwN0J0dlNMb3oyQ08wclVLQ0kK15nnKWE8159zQbuSMvzmxisCbXSn1x51
            i2XqNqNR//gKd+sUNiT8jXgkPnZdCJ9Pkvx1M6t1LjqfRp/NwJrm3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-07T20:11:19Z"
    mac: ENC[AES256_GCM,data:M4bqkcBwkHm5dDkt864B7opuYblv+GxKkiQR/u7Uol/uS2kyUE1DO10kI7TqepCVnB734Sb/RH2aIO3tn3eHZ9pKmMxxWuGkon9Td+8SiIt177eHygP2qSnIX95Jf4DbohsiXPelFjPwp6r/FfTGnfTjohDhw8IkAPff4fVcn4Y=,iv:3wvgke6DTDrmTm5fQYXUUQTRlSwAiSmhhSx//37F0cU=,tag:0xaUX2VNouCcMm6hJcH+3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
