---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.20.5
        k8s-1:
          ansible_host: 192.168.20.6
        k8s-2:
          ansible_host: 192.168.20.7
    worker:
      hosts:
        k8s-3:
          ansible_host: 192.168.20.8
          rook_devices:
            - /dev/sdb
        k8s-4:
          ansible_host: 192.168.20.9
          rook_devices:
            - /dev/sdb
        k8s-5:
          ansible_host: 192.168.20.10
          rook_devices:
            - /dev/sdb
