# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:SECHoCicFJ4UQJC80wWF6mywXII=,iv:X7m4neda54WjBGg3/vfCLjrGUroSdIFg43cxe0Lm+XE=,tag:jRa4SECB5PkkY9LHZCVseg==,type:str]
    SECRET_LOCAL_DOMAIN: ENC[AES256_GCM,data:ymyIrYIXNFw1tYP1VMlPOguNes7nTpIgcRw=,iv:bgI39LnHI3gSuNvEwod2YNBUfohsfTl0wZZzRErBywk=,tag:/aV04CzKw7xaKVQ1aR8Sbg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:y6/x5K8tCfsQtoXVhcMvF6mU1g1lqJyfkQ==,iv:4Gy6ZsvLFxv3OCTEDn8lk9NLfOcmlRwCTaoy8UpmW3Q=,tag:zlOIvEZ3+qK3VQ3QjIS//g==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:xYGZoy6maimQWVM=,iv:et+U0G2EaHACl+OyQTaM4dcmcGNrPUv232XsowiB5i4=,tag:bKWMhG3gpoExVN0UbdfGPg==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:qlEhW4dxDy4jqlI=,iv:R3FcDRb0UGO0VIHb2a//F8Y1GpZQ366Z7QkiBeD/NNg=,tag:bNMYWuQF7RppUbM+NPLJ6Q==,type:str]
    VPN_PORT: ENC[AES256_GCM,data:jFuBWKg=,iv:1+QRwgvx43kDPAr4KIbWD1/QRYqiYdxIWojON4U8Nf4=,tag:akIWFncnuqnR6n+JsbPdRQ==,type:str]
    VPN_FORWARD_PORT_1: ENC[AES256_GCM,data:QuqZRks=,iv:IJaqhrNhKYu1f0COwBg1uC+rcK81vpNIxHXP4kZ6UNE=,tag:+MZq9J4AYrIjlEuBtilNBg==,type:str]
    VPN_COUNTRY: ENC[AES256_GCM,data:4yOY,iv:JXUiGWR1ZcfaK4r6ekyP0ZsXgspdYT+e5oRqZg2hybI=,tag:Libq7Kq4udbRw4s92Qg/tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eynu35v0tpg9remal6zeecfeg9e84a2qxake027wwgdn02rdfcls7nyv8r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITDl1VEhvcUV5SERhWEp2
            ZFl0NWdXdXlRTzVXdEU1QW5BcE83STBZdWdVCnlGM2d4TnAzbDU0SHQ2c0hnNnJn
            MHQ1OVdtUzdUcklnYWMzT1g3TFg5QXcKLS0tIGFkU3U5T2hzSmNJWS9jSHRMQ3hY
            UWMxWENHWjhDenBvWFp2ZElkQXNPUFEKvzb3XxAh7hqZi8rSY0FzVOCI9inbNnCf
            PgrZqVQtb3hDxaZFmoA73YXrldwOik5DDtGbM+ZcSL3m3fVre/DwtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-25T20:23:14Z"
    mac: ENC[AES256_GCM,data:svf6vkl7kY1SZhDn0pjStBvZqBSYR/Byq7B56EBnyJZFxN05rqWhD77bTU5khsK+R4PEZLjqjOToS6nN01GpBFxtS5FJMrRfiW6vUpMapo2UA6DHHQgzKYjHgkyFYyhtOr1zaOco2016T27LU+72Vu/LQR7JykTTtcmlAE+t0K8=,iv:MqKh3aOJ2NVSYhqIW5IS7iqV+cLzgptg4ipmb+vcnmI=,tag:mE/nvOt+KKWMbsrfIHba6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
