---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Boise"
  CLUSTER-CIDR: 10.42.0.0/16
  SERVICE-CIDR: 10.43.0.0/16
  METALLB_LB_RANGE: 192.168.21.2-192.168.21.254
  METALLB_INGRESS_ADDR: 192.168.21.2
  METALLB_K8S_GATEWAY_ADDR: 192.168.21.3
  CLUSTER_CERT: "letsencrypt-production"
