---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.21.2-192.168.21.254
  METALLB_INGRESS_ADDR: 192.168.21.2
  METALLB_K8S_GATEWAY_ADDR: 192.168.21.3
  TZ: "America/Boise"
