---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: overseerr
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.29.1
    env:
      TZ: "America/Boise"
      LOG_LEVEL: "info"
    service:
      main:
        ports:
          http:
            port: 5055
      # ui:
      #   enabled: true
      #   type: LoadBalancer
      #   ports:
      #     ui:
      #       enabled: true
      #       port: 5055
      #       protocol: TCP
      #       targetPort: 5055
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "eye-circle"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "requests.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "requests.${SECRET_DOMAIN}"
            secretName: "requests-tls"
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config-v1
        mountPath: /app/config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 750Mi
