---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: error-pages
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: error-pages
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: traefik
      namespace: networking
  values:
    image:
      repository: ghcr.io/tarampampam/error-pages
      tag: 2.13.0
    env:
      TX: ${TZ}
      TEMPLATE_NAME: l7-dark
      SHOW_DETAILS: "false"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
