---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 10m
  url: ssh://git@github.com/snoopy82481/new_template_k3s
  ref:
    branch: main
  secretRef:
    name: github-deploy-key
