# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:g4PPX1h1MclGRtVdDSU450M/SXtAcJXZUrOBlGAPHKJaUaM3BUCB1rS/7qoxMAl8ENgsZrAurC0epMtcQUk5I2+5kbkemLps2/JS5g9JZMYN88/ym+20k/6E+4WqzFu7Z9peWXXo6acx1919MKLJ51iXk9FgXv/blV8Tjety1nBEdKzIONTGkns88GLnHUsjNZzT938IJadnw7wTBScI07znXhBj83NMYvLY+oDwb3dMrkO2vvNS0oZHE8fo/8WgTWYjuiHu++DGcNTIdPsRSJ6Oa26RcxZtjkQZJozSlRCYxgch5gNKq5z/3O7Dd5qlyiuWbrGDFPyZUNfUHmOTvDVlAQjDiG5turoV+jRqq8WpkHvzGED3l8LuWDgSHjoHFfx2tf+YoRR3+emxrOmiF9MC4jPcrAzj71bPSPzJ8nS1zNZHRgg/kimOHXbOH5M1tv419OIPv643aTGOMrBsoBCPU2JJidxhAsMOCJhMYAreHtkXVBvznJ1CzOciOH+kj/TyquzhyWFx4vrVD3ZPBOarySjlGGs59eIsOo3toF1wWuPjjtOOhmBbEGOamYRBKVdy4AhkJ8LsSv59vDo+jjL6EcJgtJ2GyRQBOc7ZDad34DqnwOkWgg1s5bT21c/jj2mAnDESuiS7r+/w9HFdgNC1eTpdrsVxk9d4MDl8perqpsK3iC9Wwi0pya+aOIA6FNmoValscktYXsggJYGXS5OG0QCErMOAUonMwBQeFHcYv+SVaF5jEkcKHac8tgbneZ/QarDIlHjX5GvSqQGXsO9812m7vYsz5jCBCJERO7MUNK93rDolNRmfYHjWxdzCrXn6XnTMjJ1d1HXmLDSzIYKRdAu66Uz8d5HGLuZULu+f9pPS2zeu7wq/hrD5dFb3lKgcmnK5+eVPY0JEtxa+MFoDhnoCkit/zm7HClhZ3P8FJvJVi+hDX3S862l/+MV5mnrwBBIM3wQ26trkrO54wg==,iv:MuEjsuCOBOKwCOUAvXjcK9RLQcRK7WxNWBr6RoeRiZw=,tag:gyu0x6HebT8Yjheanh2gwA==,type:str]
    known_hosts: ENC[AES256_GCM,data:2WVH40B0x6bHQa+F+jb9X9r9Pmg50tYqUluqSh55+Xg+efKyx9h1bBPBqmTh1cNM2jRpS8pNlC4nsx6RWWCaDzeL6Bu3/ILVDf9UM4FsfMepRZFYgvn0gE9//lRNStSsFwrn8v+4hsWUs+hSX2CY5LylVaRNm2v+PzE80tAZd1KKv7PKZTm77Pn5/FTy95Tpj/lm3aspWoCDqBtNLGW4MnCp7g4qpExgxSlIoWbiempyggsKFtiJAE6UV5hJJ2RwN4WYNACiAUEjnu22EeG5pC3GLBkWugj2imapq6A9KiHnFYNrgULl4wbBw/PHlrlSvbet/kTwZqBtScrHsYMbSpq5xzsACmPyaCyilgOJYdzw6SGVYSUJH38eHiq9Ks+oQTHdR8MFedcZOWLiu0TaXkwaqcvOFhFHVhCWoESEHCFxra1tlWDmzplxi6aIb8t2Kcx3279Z8HBFFzsI1eylAIddM3BMdGGykO2PRnWMTLg+kfl89dVz3SsZmk9pedFr2dh68kDlO2gyT4X8fXSDBcs1Q73t+5xywvZv+lJ62jlH88XEVJqieS4IsJi6yzJ4jx4EykqMTDeQcCEdGb3vdfRDDaedZM6g0GlaHEukiTL8d0HAYE8bz4ypv0sYY3pUrBnC1JqZixifSyTpsC1kuSpkv4R06UtNZ/MevLTLJasFlqQFb7UIUyrHh+mYld5X7R3pVeUb1B4gi62iCDhREiMUAzTRFOFuBxoYgz37fnl0svcc4EOZSQ4ouxQvrj9o33YabXsQDuTcOtRi+RU8SLzhkuF6PH///SAzPtGCsuxgXt9LSnCE2Z0l/cHCcjXAs+yQVhO8sIHV6XhRdbhAJPBH+eOo+SewlShPQQTyrw==,iv:+xTET1j8qYezf3WrMaBkW5RbZGNpet+9VVqToLS6qTw=,tag:erd9tGhwr0/8io2OfIRGag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eynu35v0tpg9remal6zeecfeg9e84a2qxake027wwgdn02rdfcls7nyv8r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VlhYd1BqZmtDS1ZQRnRZ
            SEVtVitRRmFFSU1ORVBoUlNtUkxSV0wzTkhBCnZXRktaL2RIRGthRlRQdUtwRWE2
            K29CV2VobUI5V3Y2UTVST2k1SnpQNTQKLS0tIGdhTnVscEs4cGlLeG1WL3AvcWZn
            YVJxYXFlME9qWDVyeXo4Vkx2T1FEUVEK3r4TA8XCjL51yRtU2nAR6taEMqrii/RX
            Yup7q9RNxFCfn43hdY84lAJIPEC8Wa/CcQx6F/F6m6wBUs3S59lIFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-23T20:55:57Z"
    mac: ENC[AES256_GCM,data:Ic9n2NH4Jltgg1VkfCbQvY1HQXpSYfTlNTErVe8FTMiHwGI7hnK40JD2BmgQcBJnaLr3nG8R21B4tRso4BeO6pNUVJsR4Q7N5IuVq+kogRnuKZcy/Jptd3iix/RvKVfMJg2K3dweeG4LZSVM+nkHl8uN6cdAt/DOFyk3KtOGINw=,iv:Wc9eSTWNbyTu7ejnm37v3tJV0uoJh4NE4UQJgb6INBQ=,tag:iu+hAGdyFxFvyHcF9E1apg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
