---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: prowlarr
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: cr.hotio.dev/hotio/prowlarr
      tag: nightly
      pullPolicy: Always
    env:
      TZ: "America/Boise"
      PUID: 1001
      GUID: 1001
      UMASK: 002
    service:
      # main:
      #   ports:
      #     http:
      #       port: 9696
      main:
        enabled: true
        type: LoadBalancer
        ports:
          main:
            enabled: true
            port: 9696
            protocol: TCP
            targetPort: 9696
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "eye-circle"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "prowlarr.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-v1
        mountPath: /config
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 750Mi
