---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-v1
  namespace: media
  labels:
    app.kubernetes.io/name: &name sonarr
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: ceph-block
