---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metallb-source
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/metallb/metallb.git
  ref:
    tag: v0.13.5
  ignore: |
    # exclude all
    /*
    # include crd directory
    !/config