---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app recyclarr-edge
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: recyclarr
      namespace: media
  values:
    image:
      repository: ghcr.io/recyclarr/recyclarr
      tag: edge@sha256:8786bd19cf7d08bab235f58bc11b98446329f6e19afc3df69ecb62f8d8820183
    env:
      TZ: ${TZ}
    service:
      main:
        ports:
          http:
            port: 1080
    initContainers:
      init-configs:
        image: busybox:latest@sha256:eefcea3b8ce262bc408d717cc2e1b5c99b9742d0f96adbe8f05fdb43cac6ba11
        envFrom:
          - secretRef:
              name: *app
        command:
          - "/bin/bash"
          - -c
        args:
          - "envsubst < /config/recyclarr.yaml > /shared/recyclarr.yaml"
        volumeMounts:
          - name: config
            mountPath: /config
          - name: shared
            mountPath: /shared
    persistence:
      recyclarr:
        enable: true
        type: configMap
        name: recyclarr
        subpath: recyclarr.yaml
        mountPath: /config/recyclarr.yaml
        readonly: true
      shared:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
