---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tigera-operator
  namespace: tigera-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: tigera-operator
      version: v3.24.1
      sourceRef:
        kind: HelmRepository
        name: calico-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    installation:
      enabled: true
      calicoNetwork:
        bgp: disabled
        ipPools:
          - blockSize: 26
            cidr: ${CLUSTER_CIDR}
            encapsulation: VXLANCrossSubnet
            natOutgoing: Enabled
            nodeSelector: all()
      nodeMetricsPort: 9091
      typhaMetricsPort: 9093
    apiServer:
      enabled: true
    certs:
      node:
        key:
        cert:
        commonName:
      typha:
        key:
        cert:
        commonName:
    tigeraOperator:
      image: tigera/operator
      version: v1.28.1
      registry: quay.io
      nodeSelector:
        matchExpression:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
              - "k8s-0"
    calicoctl:
      image: docker/io/calico/ctl
      tag: v3.24.1
    felixConfiguration:
      featureDetectOverride: "ChecksumOffloadBroken=true"
