---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds-metallb
  namespace: flux-system
spec:
  interval: 30m
  path: ./config/examples/crds.yaml
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: metallb-source


# ---
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   - crds.yaml
