---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: repositories
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  dependsOn:
    - name: config