---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr4k-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block
