---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vpn-gateway-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: ceph-block
