---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - downloads
  - flux-system
  - kube-system
  - media
  - networking
  # - system-upgrade
  - tigera-operator
  - vpn
