---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: internal-headers-config
  namespace: networking
spec:
  headers:
    sslRedirect: true
    sslHost: "${SECRET_LOCAL_DOMAIN}"
    stsSeconds: 315360000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    frameDeny: true
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
    contentTypeNosniff: true
    browserXSSFilter: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: internal-headers
  namespace: networking
spec:
  chain:
    middlewares:
      - name: internal-headers-config
