# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:+U6BOHguxx395M7NFcUkgveAriAJBOAZKTGkK1n8jtK8V/3RQg==,iv:n5+TdVKTncwO5kmsQYaTUgxB15KC3BdU/nxz71Lz6hw=,tag:hmEfBoU3rHFUGoDhKHVU5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eynu35v0tpg9remal6zeecfeg9e84a2qxake027wwgdn02rdfcls7nyv8r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMTM1OVJWVytrSDdIZWlR
            T1F0aVRjSVk0NjllMktVSmZTbUloNjdMRUdVClE1bVdrRk9tNUY3VS9KWUpZZVpW
            Skk4VTB3U0lscFZVcjdvdUdRT21HWGMKLS0tICswdkZUN3UweGRqZnc2N3FoeVQ2
            dGlXNXZTMzdWakN1MHZSd1ViOHVkVDAKbHPnWMmSyfVrNpeH0hFCkKOpwDUksyqE
            qPjDKY0k8G3GrOqkpoSOecrdT1bfsStGVEkbG3JzjZ6m/8SW4xSP8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-27T22:08:50Z"
    mac: ENC[AES256_GCM,data:Ho5PbadsUKYaPRUAdtE+iLu8hKS5h5jgiHwyJuyq0CuEE+3JXR8RyHwb/anDdjVzzang8DCak+FERIUUMx6NY44EC1J9RYJKMj9y4X0DwYM/bBVI+hvKQfQy5J6ESlBGTBUQ3hRg1pATrftE56QgNCQcSRjVbupYoE/pd5jXR8Y=,iv:y2CMUlCxwtMo4cKHA8n9Xkx3AZ6prUFSObzxs4dn7rc=,tag:7AwUQUq+iaoyAgwWSrIxWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
