---
name: Schedule - Renovate Helm Releases

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: "false"
        required: false
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
    paths:
      - ".github/renovate.json5"
      - ".github/renovate/**.json"

env:
  LOG_LEVEL: "debug"
  DRY_RUN: false

jobs:
  Renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify Renovate Configuration
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.2
      - name: Renovate Helm Releases
        uses: k8s-at-home/renovate-helm-releases@v1
        with:
          cluster-path: "./cluster"
      - name: Override default config from dispatch variables
        run: |
          echo "DRY_RUN=${{ github.event.inputs.dryRun || env.DRY_RUN }}" >> "${GITHUB_ENV}"
          echo "LOG_LEVEL=${{ github.event.inputs.logLevel || env.LOG_LEVEL }}" >> "${GITHUB_ENV}"

            - name: Renovate
        uses: renovatebot/github-action@v31.80.1
        with:
          configurationFile: .github/renovate.json5
          token: "${{ secrets.GITHUB_TOKEN }}"
